### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI with openjdk 9. Works with 1.8.0

### ISSUE THREAD

**Issue by TiBeN** [ervandew/eclim#561]
Hi, 
Eclimd (v2.7.1) crashes with a `java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI` exception using OpenJDK 9 but works well using OpenJDK 1.8.0. I'm on Fedora 27. Eclim Installer worked well with OpenJDK 9. Eclipse (Oxygen 2) launches correctly with OpenJDK 9 too.

Using OpenJDK 9:
```
[ben@ben-portable ~]$ java -version                                                                                                                  
openjdk version "9.0.4"              
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
[ben@ben-portable ~]$ /home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/eclimd                                               /usr/bin/java -version                                                    
openjdk version "9.0.4"              
OpenJDK Runtime Environment (build 9.0.4+11)                                                                                                         OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
JAVA_VERSION=0                                                            
                                                                                                                                                     
/usr/bin/java -d64 -Dosgi.requiredJavaVersion=1.8 -Dosgi.instance.area.default=@user.home/eclipse-workspace -XX:+UseG1GC -Xms256m -Xmx1024m -jar /usr
/local/share/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org.
eclim.application                                                                                                                                    
Install location:                                                         
    file:/usr/local/share/eclipse/                                        
Configuration file:                                                       
    file:/usr/local/share/eclipse/configuration/config.ini loaded                                                                                    
Configuration location:                                                                                                                              
    file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/                                                    
Configuration file:                                                                                                                                  
    file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/config.ini loaded                                   
Loading timestamp file from:                                                                                                                         
         file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp                     
Timestamps found:                                                                                                                                    
         config.ini in the base: 1513588010000                            
         remembered 1513588010000    
Shared configuration location:       
    file:/usr/local/share/eclipse/configuration/
Framework located:
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
        eclipse.properties not found
Framework classpath:
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
    file:/usr/local/share/eclipse/plugins/
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
Debug options:
    file:/home/ben/.options not found
Time to load bundles: 59
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Wil
l retry after the state location is initialized.
Starting application: 18296
org.eclipse.m2e.logback.configuration: Logback config file: /home/ben/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logb
ack.1.8.2.20171007-0217.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://1041.fwk210156003:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://1041.fwk210156003:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
An error has occurred. See the log file
/home/ben/eclipse-workspace/.metadata/.log.
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.7.1
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 2 more
```

Using OpenJDK 1.8.0:
```
[ben@ben-portable ~]$ java -version                                                                                                                  
openjdk version "1.8.0_161"                                                                                                                          
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
[ben@ben-portable ~]$ /home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/eclimd                                               /usr/bin/java -version                                                    
openjdk version "1.8.0_161"          
OpenJDK Runtime Environment (build 1.8.0_161-b14)                                                                                                    OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
JAVA_VERSION=8                                                            
                                                                                                                                                     
/usr/bin/java -d64 -Dosgi.requiredJavaVersion=1.8 -Dosgi.instance.area.default=@user.home/eclipse-workspace -XX:+UseG1GC -Xms256m -Xmx1024m -jar /us$
/local/share/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org$
eclim.application                                                                                                                                    
Install location:                                                         
    file:/usr/local/share/eclipse/   
Configuration file:                                                                                                                                  
    file:/usr/local/share/eclipse/configuration/config.ini loaded                                                                                    Configuration location:              
    file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/                                                    
Configuration file:                                                                                                                                  
    file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/config.ini loaded                                   
Loading timestamp file from:                                                                                                                         
         file:/home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp                     
Timestamps found:                                                                                                                                    
         config.ini in the base: 1513588010000                                                                                                       
         remembered 1513588010000                                   
Shared configuration location:                                                                                                              [10/1863]
    file:/usr/local/share/eclipse/configuration/                                                                                                     
Framework located:                                                                                                                                   
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
        eclipse.properties not found
Framework classpath:
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
    file:/usr/local/share/eclipse/plugins/
    file:/usr/local/share/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
Debug options:
    file:/home/ben/.options not found
Time to load bundles: 55
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Wil
l retry after the state location is initialized.
Starting application: 17592
org.eclipse.m2e.logback.configuration: Logback config file: /home/ben/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logb
ack.1.8.2.20171007-0217.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://1041.fwk1121647253:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://1041.fwk1121647253:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
Application Started: 22308
2018-02-03 11:55:53,461 INFO  [org.eclim.eclipse.EclimDaemon] Workspace: /home/ben/eclipse-workspace
2018-02-03 11:55:53,463 INFO  [org.eclim.eclipse.EclimDaemon] Home: /home/ben/.eclipse/org.eclipse.platform_4.7.2_1591644777_linux_gtk_x86_64/plugins
/org.eclim_2.7.1/
2018-02-03 11:55:53,463 INFO  [org.eclim.eclipse.EclimDaemon] Starting eclim...
2018-02-03 11:55:53,481 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim
2018-02-03 11:55:53,486 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim.core
2018-02-03 11:55:53,619 INFO  [org.eclim.plugin.core.CorePlugin] Loading eclim plugins...
2018-02-03 11:55:53,623 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.wst
2018-02-03 11:55:53,626 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.dltk
2018-02-03 11:55:53,627 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.pdt
2018-02-03 11:55:53,632 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.jdt
2018-02-03 11:55:53,636 INFO  [org.eclim.plugin.core.CorePlugin] Plugins loaded.
2018-02-03 11:55:53,643 INFO  [org.eclim.eclipse.EclimDaemon] Loaded plugin org.eclim.core
2018-02-03 11:55:53,647 INFO  [org.eclim.eclipse.EclimDaemon] Waiting on running jobs before starting eclimd...

(Eclipse:27810): Gtk-WARNING **: Allocating size to GtkBox 0x7f708647c440 without calling gtk_widget_get_preferred_width/height(). How does the code
know the size to allocate?

(Eclipse:27810): Gtk-WARNING **: Allocating size to GtkBox 0x7f708647c440 without calling gtk_widget_get_preferred_width/height(). How does the code
know the size to allocate?
2018-02-03 11:55:58,651 INFO  [org.eclim.eclipse.EclimDaemon] Jobs finished.
2018-02-03 11:55:58,652 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091

```

**Comment by ervandew** [comment]
This is fixed by d4670ec3f0a6f0cddb3cfe2dd69b769b0deab14c

**Comment by TiBeN** [comment]
OK great, thanks

**Comment by zhonli** [comment]
export DISPLAY=:5
